language: elixir
elixir:
  - 1.2.2
otp_release:
  - 18.2.1
install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - (cd examples/friends; mix deps.get)
script:
  - mix test
  - ECTO_POOL=poolboy mix test.adapters
  - ECTO_POOL=sbroker mix test.adapters
  - cd rumbl; mix test
