language: elixir
elixir:
  - 1.2.3
otp_release:
  - 18.2.1
install:
  - cd rumbl
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
script:
  - mix test
  - ECTO_POOL=poolboy mix test.adapters
  - ECTO_POOL=sbroker mix test.adapters
